site_name: 'Python-app'
site_description: 'Main documentation for Python-app'
repo_url: https://github.com/Tejasnk05/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Greetings?: 'docs/index.md'